sudo: required

services:
  - docker

env:
  global:
    - DJANGO_PROJECT_NAME=testsite
  matrix:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8

script:
  - make "python$PYTHON_VERSION"
  - chmod --recursive a+wrx .
  - >
    docker run
    -it
    --volume $(pwd):/var/www/app:rw
    --user dev
    "python-container:$PYTHON_VERSION"
    bash ./test.sh
