sudo: required

services:
  - docker

env:
  global:
    - DJANGO_PROJECT_NAME=testsite
  matrix:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

script:
  - make "$PYTHON_VERSION"
  - >
    docker run
    -it
    --user dev
    "python-container:$PYTHON_VERSION"
    bash -c "pipenv install django && pipenv run django-admin startproject $DJANGO_PROJECT_NAME"
