sudo: required

services:
  - docker

env:
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

script:
  - make "$PYTHON_VERSION"
  - >
    docker run
    -it
    --user dev
    "python-container:$PYTHON_VERSION"
    bash -c "PROJECT_NAME=testsite && pipenv install django && pipenv run django-admin startproject \"$PROJECT_NAME\""
