---
# This file is only used to build multiple images
services:
  python3.13:
    image: ${COMPOSE_BUILD_NAME}:3.13
    build:
      dockerfile: 3.13/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - POETRY_VERSION=2.1.3
        - VCS_REF=$VCS_REF
  python3.12:
    image: ${COMPOSE_BUILD_NAME}:3.12
    build:
      dockerfile: 3.12/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - POETRY_VERSION=2.1.3
        - VCS_REF=$VCS_REF
  python3.8:
    image: ${COMPOSE_BUILD_NAME}:3.8
    build:
      dockerfile: 3.8/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - PIPENV_VERSION=2018.11.26
        - POETRY_VERSION=1.0.5
        - PYTHON_VERSION=3.8
        - VCS_REF=$VCS_REF
  python3.7:
    image: ${COMPOSE_BUILD_NAME}:3.7
    build:
      dockerfile: 3.7/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - PIPENV_VERSION=2018.11.26
        - POETRY_VERSION=1.0.5
        - PYTHON_VERSION=3.7
        - VCS_REF=$VCS_REF
  python3.6:
    image: ${COMPOSE_BUILD_NAME}:3.6
    build:
      dockerfile: 3.6/Dockerfile
      context: .
      args:
        - BUILD_DATE=$BUILD_DATE
        - PIPENV_VERSION=2018.11.26
        - POETRY_VERSION=1.0.5
        - PYTHON_VERSION=3.6
        - VCS_REF=$VCS_REF
